### ISSUE TITLE
Change link in the repository description

### ISSUE THREAD

**Issue by sidsbrmnn** [theultimateshyam/theultimateshyam.github.io#14]

**Comment by theultimateshyam** [comment]
Resolved with commit 317eb4b

**Comment by sidsbrmnn** [comment]
<img width="317" alt="image" src="https://user-images.githubusercontent.com/35731243/88484389-d2aa4780-cf8b-11ea-9421-1a5998953b50.png">

Still not fixed.
